version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sonya
      POSTGRES_PASSWORD: 133755
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build:
      context: ./backend/user-service
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  vehicle-service:
    build:
      context: ./backend/vehicle-service
    env_file:
      - ./.env
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - rabbitmq
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - vehicle-service

volumes:
  postgres-data:
